import Head from "next/head";
import { About } from "../components/About";
import { Contact } from "../components/Contact";
import { Mail } from "../components/Mail";
import { Projects } from "../components/Projects/Projects";
import { Skills } from "../components/Skills/Skills";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio App.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Mail />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
  );
}
